# Generated by Django 3.2.7 on 2021-10-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.BigIntegerField()),
                ('num2', models.BigIntegerField()),
                ('resultado', models.BigIntegerField()),
            ],
        ),
    ]
