# Generated by Django 3.2.7 on 2021-10-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicar', '0002_alter_operacion_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='num1',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='num2',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='resultado',
            field=models.CharField(max_length=50),
        ),
    ]
